; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = base


[env:base]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
; upload_port = COM3
; monitor_port = COM3
build_src_filter = +<main.cpp> -<mac_finder.cpp> -<arcade_stick.cpp>

build_flags=
    -Isrc/Helpers
    -DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
    -DDEFAULT_BAUD_RATE=115200


lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit SSD1306 @ ^2.5.9
    https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32.git



[env:arcade_stick]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<arcade_stick.cpp> -<main.cpp> -<mac_finder.cpp>



[env:mac_finder]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<mac_finder.cpp> -<main.cpp> -<arcade_stick.cpp>

    
